name: AmazingFactions
version: '1.0'
main: org.vera.amazingFactions.AmazingFactions
api-version: '1.20'
commands:
  create:
    description: Creates a new faction
    permission: amazing-factions.create

softdepend: [PlaceholderAPI]
