name: AmazingFactions
version: '1.0'
main: org.vera.amazingFactions.AmazingFactions
api-version: '1.20'
commands:
  create:
    description: Adds a user to a material cooldown
    usage: "[AmazingFactions] - Usage: /create <name> <description> <list of the users>"
    permission: amazing-factions.create

softdepend: [PlaceholderAPI]
