name: AmazingFactions
version: '1.0'
main: org.vera.amazingFactions.AmazingFactions
api-version: '1.20'
commands:
  create:
    description: Creates a new faction
    permission: amazing-factions.create
  delete:
    description: Delete a faction
    permission: amazing-factions.delete

softdepend: [ PlaceholderAPI ]
